from _bootstrap import ROOT
from ashare_premarket.research.goal_liquidity_evidence_acceptance_contract01 import audit_goal_liquidity_evidence_acceptance_contract01
if __name__=="__main__":raise SystemExit(0 if audit_goal_liquidity_evidence_acceptance_contract01(ROOT) else 1)
