from __future__ import annotations

BOOTSTRAP_DATE = "2026-06-21"
SOURCE_REPOSITORY = "RyanLu0203/A_share_market_analysis_and_prediction"
TARGET_REPOSITORY = "RyanLu0203/A_share_premarket_core"

APPROVED_SYMBOLS = ["002475.SZ", "600036.SH"]
BLOCKED_SYMBOLS = ["000625.SZ", "000858.SZ", "601138.SH", "601208.SH"]

PUBLIC_COMMANDS = [
    "scripts/audit_existing_modules.py",
    "scripts/build_pit_signal_snapshot.py",
    "scripts/audit_pit_signal_snapshot.py",
    "scripts/build_label_snapshot.py",
    "scripts/audit_label_snapshot.py",
    "scripts/build_model_ready_candidate_dataset.py",
    "scripts/audit_feature_label_leakage.py",
    "scripts/run_stage6a_blocker_repair.py",
    "scripts/run_baseline_scoring_skeleton.py",
    "scripts/audit_baseline_scoring_skeleton.py",
    "scripts/run_supervised_baseline_training.py",
    "scripts/audit_supervised_baseline_training.py",
    "scripts/run_current_trunk_validation.py",
    "scripts/run_program_validation_profile.py",
    "scripts/run_safety_gate.py",
    "scripts/run_adapter_audit.py",
    "scripts/run_workflow_diagnostics.py",
    "scripts/audit_workflow_status.py",
    "scripts/run_e2e_trunk_verification_through_goal06b.py",
    "scripts/run_e2e_trunk_validation_through_goal06b.py",
    "scripts/run_goal06b_regression_suite.py",
]

REGRESSION_COMMANDS = [
    "python scripts/audit_existing_modules.py",
    "python scripts/build_pit_signal_snapshot.py",
    "python scripts/audit_pit_signal_snapshot.py",
    "python scripts/build_label_snapshot.py",
    "python scripts/audit_label_snapshot.py",
    "python scripts/build_model_ready_candidate_dataset.py",
    "python scripts/audit_feature_label_leakage.py",
    "python scripts/run_stage6a_blocker_repair.py --no-network",
    "python scripts/run_baseline_scoring_skeleton.py",
    "python scripts/audit_baseline_scoring_skeleton.py",
    "python scripts/run_supervised_baseline_training.py",
    "python scripts/audit_supervised_baseline_training.py",
    "python scripts/run_workflow_diagnostics.py",
]

REQUIRED_OUTPUTS = [
    "outputs/audits/module_health_matrix.csv",
    "outputs/audits/stage5_readiness_report.md",
    "outputs/features/daily_premarket_signal_snapshot.csv",
    "outputs/audits/pit_signal_snapshot_audit.md",
    "outputs/audits/pit_signal_quality_report.md",
    "outputs/audits/stage5b_readiness_report.md",
    "outputs/labels/daily_label_snapshot.csv",
    "outputs/audits/label_snapshot_audit.md",
    "outputs/audits/stage5c_readiness_report.md",
    "outputs/datasets/model_ready_candidate_dataset.csv",
    "outputs/datasets/live_feature_manifest.csv",
    "outputs/datasets/label_manifest.csv",
    "outputs/datasets/excluded_column_manifest.csv",
    "outputs/audits/feature_label_merge_audit.md",
    "outputs/audits/leakage_audit_report.md",
    "outputs/audits/stage6a_readiness_report.md",
    "outputs/stage6a/STAGE6A_repair_candidate_dataset.csv",
    "outputs/stage6a/STAGE6A_live_feature_manifest.csv",
    "outputs/stage6a/STAGE6A_label_manifest.csv",
    "outputs/stage6a/STAGE6A_baseline_score_snapshot.csv",
    "outputs/stage6a/STAGE6A_score_feature_usage_manifest.csv",
    "outputs/audits/baseline_scoring_skeleton_audit.md",
    "outputs/audits/stage6b_readiness_report.md",
    "outputs/stage6b/STAGE6B_training_dataset.csv",
    "outputs/stage6b/STAGE6B_feature_manifest.csv",
    "outputs/stage6b/STAGE6B_label_manifest.csv",
    "outputs/stage6b/STAGE6B_prediction_preview.csv",
    "outputs/models/goal06b/baseline_training_summary.json",
    "outputs/models/goal06b/baseline_model_registry_stub.json",
    "outputs/models/goal06b/review_only_model_card.md",
    "outputs/audits/supervised_baseline_training_audit.md",
    "outputs/audits/stage6c_readiness_report.md",
    "outputs/audits/classified_capability_catalog_through_goal06b.csv",
    "outputs/audits/active_trunk_module_map.csv",
    "outputs/audits/legacy_excluded_from_clean_repo_manifest.csv",
    "outputs/audits/legacy_excluded_from_clean_repo_summary.md",
    "outputs/audits/active_workflow_map_through_goal06b.md",
    "outputs/audits/e2e_active_trunk_refactor_audit_through_goal06b.md",
    "outputs/audits/e2e_trunk_verification_report_through_goal06b.md",
    "outputs/audits/e2e_trunk_validation_report_through_goal06b.md",
    "outputs/audits/goal06b_regression_suite_report.md",
    "outputs/audits/goal06b_clean_repo_bootstrap_readiness_report.md",
    "outputs/audits/workflow_status_audit.md",
    "outputs/audits/workflow_status_table.csv",
    "outputs/audits/workflow_diagram_update_report.md",
    "outputs/diagnostics/workflow_diagnostic_summary.md",
    "outputs/diagnostics/command_failure_catalog.csv",
    "outputs/diagnostics/capability_health_matrix.csv",
    "outputs/diagnostics/run_detail_manifest.csv",
    "outputs/diagnostics/known_warnings_and_non_blockers.md",
    "outputs/diagnostics/next_worker_runbook.md",
]

LOCKED_KEYWORDS = [
    "dqn",
    "reinforcement_learning",
    "risk_overlay",
    "position_band",
    "recommendation",
    "dashboard",
    "paper_trading",
    "broker",
    "live_trading",
    "production_db_write",
]
