from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Capability:
    capability_id: str
    capability_name: str
    capability_class: str
    stage_or_goal: str
    owner_module: str
    public_scripts: tuple[str, ...]
    required_outputs: tuple[str, ...]


CLASS_A_CAPABILITIES: tuple[Capability, ...] = (
    Capability("project_operating_system", "Project operating system", "CLASS_A_REQUIRED_ACTIVE", "Project Start", "ashare_premarket.core", ("scripts/run_current_trunk_validation.py",), ("PROJECT_STATE.md", "README.md", "CODEX.md", "AGENTS.md", "ROADMAP.md")),
    Capability("universe_symbol_governance", "Universe and symbol governance", "CLASS_A_REQUIRED_ACTIVE", "Project Start", "ashare_premarket.universe", ("scripts/run_safety_gate.py",), ("configs/universe/approved_symbols.csv", "configs/universe/blocked_symbols.csv")),
    Capability("trading_calendar", "Trading calendar", "CLASS_A_REQUIRED_ACTIVE", "Project Start", "ashare_premarket.data", ("scripts/run_e2e_trunk_validation_through_goal06b.py",), ("configs/project/trading_calendar.csv",)),
    Capability("module_health_gate", "Module health gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-04.5", "ashare_premarket.validation", ("scripts/audit_existing_modules.py",), ("outputs/audits/module_health_matrix.csv", "outputs/audits/stage5_readiness_report.md")),
    Capability("data_source_health", "Data source health", "CLASS_A_REQUIRED_ACTIVE", "GOAL-04.5", "ashare_premarket.data", ("scripts/audit_existing_modules.py",), ("configs/providers/source_health_contract.csv",)),
    Capability("market_context_contract", "Market context contract", "CLASS_A_REQUIRED_ACTIVE", "GOAL-04.5", "ashare_premarket.market", ("scripts/build_pit_signal_snapshot.py",), ("outputs/features/daily_premarket_signal_snapshot.csv",)),
    Capability("sector_context_contract", "Sector context contract", "CLASS_A_REQUIRED_ACTIVE", "GOAL-04.5", "ashare_premarket.sector", ("scripts/build_pit_signal_snapshot.py",), ("outputs/features/daily_premarket_signal_snapshot.csv",)),
    Capability("stock_ohlcv_contract", "Stock OHLCV contract", "CLASS_A_REQUIRED_ACTIVE", "GOAL-04.5", "ashare_premarket.data", ("scripts/build_pit_signal_snapshot.py",), ("outputs/features/daily_premarket_signal_snapshot.csv",)),
    Capability("event_metadata_contract", "Event metadata contract", "CLASS_A_REQUIRED_ACTIVE", "GOAL-04.5", "ashare_premarket.events", ("scripts/build_pit_signal_snapshot.py",), ("outputs/features/daily_premarket_signal_snapshot.csv",)),
    Capability("nlp_contract_gate", "NLP contract gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-04.5", "ashare_premarket.nlp", ("scripts/build_pit_signal_snapshot.py",), ("outputs/features/daily_premarket_signal_snapshot.csv",)),
    Capability("pit_signal_store", "PIT signal store", "CLASS_A_REQUIRED_ACTIVE", "GOAL-05A", "ashare_premarket.features", ("scripts/build_pit_signal_snapshot.py", "scripts/audit_pit_signal_snapshot.py"), ("outputs/features/daily_premarket_signal_snapshot.csv", "outputs/audits/pit_signal_snapshot_audit.md")),
    Capability("source_availability_gate", "Source availability gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-05A", "ashare_premarket.features", ("scripts/audit_pit_signal_snapshot.py",), ("outputs/audits/pit_signal_quality_report.md",)),
    Capability("signal_quality", "Signal quality", "CLASS_A_REQUIRED_ACTIVE", "GOAL-05A", "ashare_premarket.features", ("scripts/audit_pit_signal_snapshot.py",), ("outputs/audits/stage5b_readiness_report.md",)),
    Capability("label_contract", "Label contract and builder", "CLASS_A_REQUIRED_ACTIVE", "GOAL-05B", "ashare_premarket.labels", ("scripts/build_label_snapshot.py", "scripts/audit_label_snapshot.py"), ("outputs/labels/daily_label_snapshot.csv", "outputs/audits/label_snapshot_audit.md")),
    Capability("benchmark_contract", "Benchmark contract", "CLASS_A_REQUIRED_ACTIVE", "GOAL-05B", "ashare_premarket.labels", ("scripts/build_label_snapshot.py",), ("outputs/labels/daily_label_snapshot.csv",)),
    Capability("feature_label_merge", "Feature-label merge", "CLASS_A_REQUIRED_ACTIVE", "GOAL-05C", "ashare_premarket.datasets", ("scripts/build_model_ready_candidate_dataset.py",), ("outputs/datasets/model_ready_candidate_dataset.csv",)),
    Capability("leakage_audit", "Leakage audit", "CLASS_A_REQUIRED_ACTIVE", "GOAL-05C", "ashare_premarket.datasets", ("scripts/audit_feature_label_leakage.py",), ("outputs/audits/leakage_audit_report.md",)),
    Capability("stage6a_repair_panel", "Stage 6A repair panel", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06A", "ashare_premarket.scoring", ("scripts/run_stage6a_blocker_repair.py",), ("outputs/stage6a/STAGE6A_repair_candidate_dataset.csv",)),
    Capability("baseline_scoring_skeleton", "Baseline scoring skeleton", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06A", "ashare_premarket.scoring", ("scripts/run_baseline_scoring_skeleton.py", "scripts/audit_baseline_scoring_skeleton.py"), ("outputs/stage6a/STAGE6A_baseline_score_snapshot.csv", "outputs/audits/baseline_scoring_skeleton_audit.md")),
    Capability("supervised_baseline_training_gate", "Supervised baseline training gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06B", "ashare_premarket.training", ("scripts/run_supervised_baseline_training.py", "scripts/audit_supervised_baseline_training.py"), ("outputs/stage6b/STAGE6B_training_dataset.csv", "outputs/models/goal06b/baseline_training_summary.json")),
    Capability("current_trunk_validation", "Current trunk validation", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06B", "ashare_premarket.validation", ("scripts/run_current_trunk_validation.py",), ("outputs/audits/e2e_trunk_validation_report_through_goal06b.md",)),
    Capability("program_validation_profile", "Program validation profile", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06B", "ashare_premarket.validation", ("scripts/run_program_validation_profile.py",), ("configs/validation/validation_profile.yaml",)),
    Capability("safety_gate", "Safety gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06B", "ashare_premarket.ops", ("scripts/run_safety_gate.py",), ("outputs/audits/safety_gate_report.md",)),
    Capability("adapter_audit", "Adapter audit", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06B", "ashare_premarket.ops", ("scripts/run_adapter_audit.py",), ("outputs/audits/adapter_audit_report.md",)),
    Capability("workflow_diagnostics", "Workflow diagnostics", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06B", "ashare_premarket.diagnostics", ("scripts/run_workflow_diagnostics.py",), ("outputs/diagnostics/workflow_diagnostic_summary.md",)),
    Capability("goal06c_expanded_validation", "GOAL-06C expanded validation panel", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C", "ashare_premarket.validation.stage6c", ("scripts/build_stage6c_expanded_validation_dataset.py", "scripts/audit_stage6c_expanded_validation.py"), ("outputs/stage6c/STAGE6C_expanded_validation_dataset.csv", "outputs/audits/stage6c_expanded_validation_audit.md")),
    Capability("goal06c_ranking_baselines", "GOAL-06C ranking baselines", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C", "ashare_premarket.validation.stage6c", ("scripts/run_stage6c_ranking_baselines.py", "scripts/audit_stage6c_ranking_baselines.py"), ("outputs/stage6c/STAGE6C_ranking_baseline_scores.csv", "outputs/stage6c/STAGE6C_ranking_metrics.csv", "outputs/audits/stage6c_ranking_baseline_audit.md")),
    Capability("goal06c_walk_forward_diagnostics", "GOAL-06C walk-forward diagnostics", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C", "ashare_premarket.validation.stage6c", ("scripts/run_stage6c_walk_forward_validation.py", "scripts/run_goal06c_expanded_validation.py"), ("outputs/stage6c/STAGE6C_walk_forward_diagnostics.csv", "outputs/stage6c/STAGE6C_ranking_stability_diagnostics.csv", "outputs/audits/stage6c_readiness_report.md")),
    Capability("goal06c5_storage_policy", "GOAL-06C.5 local research storage policy", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.5", "ashare_premarket.storage.policy", ("scripts/audit_storage_policy.py",), ("configs/storage/storage_policy.yaml", "docs/storage/DATA_STORAGE_ARCHITECTURE.md", "outputs/audits/storage_policy_audit.md")),
    Capability("goal06c5_data_bundle_manifest", "GOAL-06C.5 data bundle manifest", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.5", "ashare_premarket.storage.policy", ("scripts/build_data_bundle_manifest.py", "scripts/audit_data_bundle_manifest.py"), ("outputs/audits/data_bundle_manifest_summary.md", "outputs/audits/data_bundle_manifest_summary.json", "outputs/audits/data_bundle_manifest_audit.md")),
    Capability("goal06c5_source_coverage", "GOAL-06C.5 source, universe, and calendar coverage", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.5", "ashare_premarket.data.coverage", ("scripts/audit_data_source_coverage.py",), ("outputs/audits/data_source_coverage_audit.md", "outputs/audits/source_symbol_coverage_matrix.csv", "outputs/audits/source_date_coverage_matrix.csv", "outputs/audits/source_gap_analysis.md")),
    Capability("goal06c5_engineering_pit_panel", "GOAL-06C.5 engineering PIT signal panel sample", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.5", "ashare_premarket.features.panel_expansion", ("scripts/build_engineering_pit_signal_panel.py", "scripts/audit_engineering_pit_signal_panel.py"), ("outputs/features/engineering_pit_signal_panel_sample.csv", "outputs/audits/engineering_pit_signal_panel_audit.md")),
    Capability("goal06c5_engineering_label_panel", "GOAL-06C.5 engineering label panel sample", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.5", "ashare_premarket.labels.panel_expansion", ("scripts/build_engineering_label_panel.py", "scripts/audit_engineering_label_panel.py"), ("outputs/labels/engineering_label_panel_sample.csv", "outputs/audits/engineering_label_panel_audit.md")),
    Capability("goal06c5_engineering_stage6c_panel", "GOAL-06C.5 Stage 6C engineering panel gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.5", "ashare_premarket.validation.engineering_panel", ("scripts/rebuild_stage6c_from_engineering_panel.py",), ("outputs/stage6c/STAGE6C_engineering_expanded_validation_dataset_sample.csv", "outputs/audits/stage6c_engineering_panel_audit.md", "outputs/audits/engineering_panel_readiness_report.md", "outputs/audits/active_path_replacement_audit.md")),
    Capability("goal06c6_provider_failure_classification", "GOAL-06C.6 provider failure classification", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.6", "ashare_premarket.providers.failure_classification", ("scripts/audit_provider_failure_classification.py",), ("outputs/audits/provider_failure_classification_audit.md", "outputs/audits/provider_failure_summary.md", "outputs/audits/provider_failure_summary.json", "outputs/audits/goal06c6_failure_taxonomy_report.md", "outputs/audits/goal06c6_failure_taxonomy_report.json")),
    Capability("goal06c6_akshare_provider_contract", "GOAL-06C.6 AKShare provider contract", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.6", "ashare_premarket.providers.akshare_provider", ("scripts/run_akshare_engineering_pilot_ingestion.py",), ("configs/providers/akshare_provider_config.yaml", "outputs/audits/akshare_provider_attempt_summary.csv", "outputs/audits/provider_failure_events.csv", "outputs/audits/goal06c6_network_isolation_report.md", "outputs/audits/goal06c6_network_isolation_report.json")),
    Capability("goal06c6_source_backed_local_bundle", "GOAL-06C.6 source-backed local bundle gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.6", "ashare_premarket.providers.ingestion", ("scripts/build_source_backed_local_bundle.py", "scripts/audit_source_backed_local_bundle.py", "scripts/run_goal06c6_source_backed_engineering_pilot_bundle.py"), ("outputs/audits/source_backed_bundle_manifest_summary.json", "outputs/audits/source_backed_local_bundle_audit.md")),
    Capability("goal06c6_source_backed_pit_label_panels", "GOAL-06C.6 source-backed PIT and label panel builders", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.6", "ashare_premarket.providers.ingestion", ("scripts/build_source_backed_pit_signal_panel.py", "scripts/build_source_backed_label_panel.py"), ("outputs/samples/source_backed_pit_signal_panel_sample.csv", "outputs/samples/source_backed_label_panel_sample.csv", "outputs/audits/source_backed_pit_signal_panel_audit.md", "outputs/audits/source_backed_label_panel_audit.md")),
    Capability("goal06c6_source_backed_stage6c_panel", "GOAL-06C.6 source-backed Stage 6C engineering panel gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.6", "ashare_premarket.providers.ingestion", ("scripts/rebuild_stage6c_source_backed_engineering_panel.py", "scripts/audit_stage6c_source_backed_engineering_panel.py"), ("outputs/stage6c/STAGE6C_source_backed_engineering_panel_coverage_summary.csv", "outputs/samples/stage6c_source_backed_engineering_panel_sample.csv", "outputs/audits/stage6c_source_backed_engineering_panel_audit.md", "outputs/audits/goal06c6_readiness_report.md")),
    Capability("goal06c7_provider_ladder", "GOAL-06C.7 provider ladder engineering pilot gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.7", "ashare_premarket.providers.provider_ladder", ("scripts/run_goal06c7_provider_ladder_engineering_data_base_expansion.py", "scripts/audit_workflow_cleanliness.py"), ("outputs/audits/goal06c7_readiness_report.md", "outputs/audits/workflow_cleanliness_audit.md", "outputs/stage6c/STAGE6C_source_backed_engineering_panel_coverage_summary.csv")),
    Capability("goal06c7_browser_assisted_optional_provider", "GOAL-06C.7 optional browser-assisted finance ingestion", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06C.7", "ashare_premarket.providers.browser_assisted_provider", ("scripts/run_browser_assisted_finance_ingestion.py", "scripts/audit_browser_assisted_provider.py"), ("outputs/audits/browser_assisted_provider_audit.md", "outputs/audits/browser_assisted_provider_events.csv")),
    Capability("goal06d_feature_split_contract", "GOAL-06D feature and split contract gate", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06D", "ashare_premarket.models.goal06d", ("scripts/audit_goal06d_feature_contract.py", "scripts/audit_goal06d_split.py"), ("configs/models/goal06d_feature_contract.yaml", "configs/models/goal06d_split_config.yaml", "outputs/audits/goal06d_feature_contract_audit.md", "outputs/audits/goal06d_split_audit.md")),
    Capability("goal06d_model_comparison", "GOAL-06D review-only model comparison", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06D", "ashare_premarket.models.goal06d", ("scripts/run_goal06d_model_comparison_calibration.py", "scripts/audit_goal06d_model_comparison.py"), ("outputs/models/goal06d/model_comparison_summary.csv", "outputs/models/goal06d/model_metric_by_fold.csv", "outputs/models/goal06d/model_metric_by_target.csv", "outputs/models/goal06d/model_selection_rationale.md", "outputs/audits/goal06d_model_comparison_audit.md")),
    Capability("goal06d_calibration_stability", "GOAL-06D calibration and stability diagnostics", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06D", "ashare_premarket.models.goal06d", ("scripts/audit_goal06d_calibration.py", "scripts/audit_goal06d_stability.py"), ("outputs/models/goal06d/calibration_summary.csv", "outputs/models/goal06d/stability_summary.csv", "outputs/models/goal06d/fold_metrics.csv", "outputs/models/goal06d/symbol_stability_summary.csv", "outputs/models/goal06d/feature_stability_summary.csv", "outputs/audits/goal06d_calibration_audit.md", "outputs/audits/goal06d_stability_audit.md")),
    Capability("goal06d_governance_boundary", "GOAL-06D governance and downstream boundary locks", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06D", "ashare_premarket.models.goal06d", ("scripts/audit_goal06d_governance.py", "scripts/audit_goal06d_boundary_locks.py"), ("outputs/audits/goal06d_governance_audit.md", "outputs/audits/goal06d_boundary_lock_audit.md", "outputs/audits/goal06d_readiness_report.md")),
    Capability("goal06d1_warning_repair", "GOAL-06D.1 calibration and stability warning repair", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06D.1", "ashare_premarket.models.goal06d1", ("scripts/run_goal06d1_calibration_stability_warning_repair.py", "scripts/audit_goal06d1_score_repair.py"), ("outputs/models/goal06d1/target_horizon_comparison.csv", "outputs/models/goal06d1/score_variant_comparison.csv", "outputs/models/goal06d1/model_comparison_repair_summary.csv", "outputs/audits/goal06d1_readiness_report.md")),
    Capability("goal06d1_calibration_feature_provider", "GOAL-06D.1 calibration, feature, and provider diagnostics", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06D.1", "ashare_premarket.models.goal06d1", ("scripts/audit_goal06d1_calibration_repair.py", "scripts/audit_goal06d1_feature_sign_stability.py", "scripts/audit_goal06d1_provider_concentration_disclosure.py"), ("outputs/models/goal06d1/calibration_repair_summary.csv", "outputs/models/goal06d1/feature_sign_stability_repair.csv", "outputs/models/goal06d1/provider_source_concentration_summary.csv", "outputs/audits/goal06d1_calibration_repair_audit.md", "outputs/audits/goal06d1_feature_sign_stability_audit.md", "outputs/audits/goal06d1_provider_concentration_disclosure.md")),
    Capability("goal06d1_governance_v2_lock", "GOAL-06D.1 governance and locked V2 factor placeholder", "CLASS_A_REQUIRED_ACTIVE", "GOAL-06D.1", "ashare_premarket.models.goal06d1", ("scripts/audit_goal06d1_governance.py", "scripts/audit_goal06d1_boundary_locks.py"), ("configs/factors/v2_factor_research_contract.yaml", "docs/factors/V2_FACTOR_RESEARCH_INTERFACE.md", "outputs/audits/goal06d1_governance_audit.md", "outputs/audits/goal06d1_boundary_lock_audit.md")),
    Capability("goal07a_input_output_contracts", "GOAL-07A allowed input and future output schema design", "CLASS_A_REQUIRED_ACTIVE", "GOAL-07A", "ashare_premarket.risk_design.goal07a", ("scripts/run_goal07a_risk_overlay_design_gate.py", "scripts/audit_goal07a_allowed_input_contract.py", "scripts/audit_goal07a_output_schema.py"), ("configs/risk/goal07a_allowed_input_contract.yaml", "configs/risk/goal07a_future_risk_overlay_output_schema.yaml", "outputs/audits/goal07a_allowed_input_contract_audit.md", "outputs/audits/goal07a_output_schema_audit.md")),
    Capability("goal07a_rules_state_warning_mapping", "GOAL-07A risk rule catalog, state machine, and warning mapping design", "CLASS_A_REQUIRED_ACTIVE", "GOAL-07A", "ashare_premarket.risk_design.goal07a", ("scripts/audit_goal07a_risk_rule_catalog.py", "scripts/audit_goal07a_state_machine.py", "scripts/audit_goal07a_upstream_warning_mapping.py"), ("configs/risk/goal07a_risk_rule_catalog.yaml", "configs/risk/goal07a_risk_state_machine.yaml", "configs/risk/goal07a_upstream_warning_mapping.yaml", "outputs/audits/goal07a_risk_rule_catalog_audit.md", "outputs/audits/goal07a_state_machine_audit.md", "outputs/audits/goal07a_upstream_warning_mapping_audit.md")),
    Capability("goal07a_governance_boundary_v2_lock", "GOAL-07A design-only governance boundary and V2 factor lock", "CLASS_A_REQUIRED_ACTIVE", "GOAL-07A", "ashare_premarket.risk_design.goal07a", ("scripts/audit_goal07a_governance_boundary.py", "scripts/audit_goal07a_boundary_locks.py", "scripts/audit_goal07a_v2_factor_lock.py"), ("docs/risk/GOAL07A_RISK_OVERLAY_DESIGN_ONLY_BOUNDARY.md", "outputs/audits/goal07a_governance_boundary_audit.md", "outputs/audits/goal07a_boundary_lock_audit.md", "outputs/audits/goal07a_v2_factor_lock_audit.md", "outputs/audits/goal07a_readiness_report.md")),
    Capability("goal07a1_design_review_unlock_readiness", "GOAL-07A.1 risk overlay design review and GOAL-07B unlock readiness", "CLASS_A_REQUIRED_ACTIVE", "GOAL-07A.1", "ashare_premarket.risk_design.goal07a1", ("scripts/run_goal07a1_risk_overlay_design_review_gate.py", "scripts/audit_goal07a1_input_contract_readiness.py", "scripts/audit_goal07a1_output_schema_safety.py", "scripts/audit_goal07a1_rule_convertibility.py", "scripts/audit_goal07a1_state_machine_review.py", "scripts/audit_goal07a1_warning_policy.py", "scripts/audit_goal07a1_boundary_locks.py"), ("configs/risk/goal07a1_design_review_policy.yaml", "outputs/audits/goal07a1_design_review_report.md", "outputs/audits/goal07a1_unlock_readiness_manifest.json", "outputs/audits/goal07a1_warning_classification.csv")),
)
